include:
  # Left / Right only (no dongle for now)
  - board: nice_nano
    shield: charybdis_left

  - board: nice_nano
    shield: charybdis_right

  # Optional but recommended reset
  - board: nice_nano
    shield: settings_reset
