include:
  - board: xiao_ble
    shield: charybdis_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=n

  - board: nice_nano
    shield: charybdis_left

  - board: nice_nano
    shield: charybdis_right

  - board: xiao_ble
    shield: settings_reset

  - board: nice_nano
    shield: settings_reset
